@apiURL = http://localhost:3001/boards/

GET {{apiURL}}

###

GET {{apiURL}}1

###

POST {{apiURL}}
Content-Type: application/json

{
    "name": "will be dltd",
    "description": "byeeeeeee"
}

###
DELETE {{apiURL}}6

###
GET {{apiURL}}1/cards

###
PUT {{apiURL}}cards/6
Content-Type: application/json
{
    "title": "Updated Card Title",
    "content": "Updated content for the card.",
    "positionX": 150,
    "positionY": 250
}

